### ISSUE TITLE
Adding PR Guidelines for Contributing.md

### ISSUE THREAD

**Issue by allanoguis** [abdeLKabir-56/wander#10]
I will add more information regarding PR guidelines before submitting a PR to help direct contributors to make pull requests right.

**Comment by abdeLKabir-56** [comment]
@allanoguis ah yes I agree with you , you are free to add it

**Comment by allanoguis** [comment]
@abdeLKabir-56 I created pull request #13 to fix this issue. Please add `hacktoberfest-accepted` tag also. Thank you
