### ISSUE TITLE
BUg-readme

### ISSUE THREAD

**Issue by Mukesh-ghildiyal** [abdeLKabir-56/wander#14]
there is not defined in readme.md file how to open this repo on your local,so might be contributors have faces this type of issues

**Comment by TanishaMehta17** [comment]
@abdeLKabir-56  Can you please assign me this task

**Comment by TanishaMehta17** [comment]
@abdeLKabir-56  I have raised a PR please do review it and let me know if you need any changes.

**Comment by Mukesh-ghildiyal** [comment]
@TanishaMehta17 you will trying to be over smart just raise your own issues and then make a PR.
