### ISSUE TITLE
Include CONTRIBUTING and CODE_OF_CONDUCT files

### ISSUE THREAD

**Issue by bypratyush** [abdeLKabir-56/wander#9]
I'd like to update the repository with the CONTRIBUTING file and the CODE_OF_CONDUCT file so that everyone can have a clear idea of creating forks and contributing effortlessly.

Can you please assign this task to me?

**Comment by abdeLKabir-56** [comment]
@pratyush090506 yes you are free to add it

**Comment by bypratyush** [comment]
Can you please assign this task to me?

**Comment by bypratyush** [comment]
@abdeLKabir-56 Added the Pull request for this issue. Kindly review it

**Comment by bypratyush** [comment]
Kindly add the hacktoberfest label as well.

**Comment by bypratyush** [comment]
Could you please add the Hacktoberfest label to the entire repo
